### ISSUE TITLE
ClickAwayListener does not work with TextField

### ISSUE THREAD

**Issue by semopz** [stackworx/formik-material-ui#139]
Library version: 2.0.0-alpha.3
Material UI version: 4.9.1
Formik version 2.1.4
Repro: Look in Console -> https://codesandbox.io/s/click-away-listener-jtkz5

Wrapping a TextField (from formik-material-ui) with a [ClickAwayListener](https://material-ui.com/api/click-away-listener/) shows the following warnings in the console. It also prevents the ClickAwayListener from functioning correctly.

Replacing `TextField` with  with`MuiTextField` solves the problem.

>Warning: Failed prop type: Invalid prop `children` supplied to `ForwardRef(ClickAwayListener)`. Expected an element that can hold a ref. Did you accidentally use a plain function component for an element instead? For more information see https://material-ui.com/r/caveat-with-refs-guide
    in ForwardRef(ClickAwayListener) (at demo.tsx:58)
    in Formik (at demo.tsx:31)
    in App (at index.tsx:6)

>Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
>
>Check the render method of `ForwardRef(ClickAwayListener)`.
    in FormikMaterialUITextField (at demo.tsx:59)
    in ForwardRef(ClickAwayListener) (at demo.tsx:58)
    in form (created by Form)
    in Form (at demo.tsx:55)
    in Formik (at demo.tsx:31)
    in App (at index.tsx:6)

**Comment by cliedeman** [comment]
Looks like this is fixed in the latest version - https://codesandbox.io/s/click-away-listener-um65b

**Comment by semopz** [comment]
Still doesn't work. To replicate, bring up the popover by clicking on the "i" icon and then click on Submit. Desired result would be for the popover to go away. If you wrap the `Field` inside a `div`, it works as intended.

**Comment by cliedeman** [comment]
fixed by wrapping a Box around the field. 

More info: https://material-ui.com/guides/composition/#caveat-with-refs.

To fix this in the library we would have to wrap all components in React.forwardRef and I don't think we should

**Comment by semopz** [comment]
Wrapping is the solution
